### PR TITLE
Update [fix] Special characters aren’t saved correctly

### PR DESCRIPTION
**Pull request by Galixte**
Hi @DavidIQ,

could you merge this, please?

Also, I noted that the log messages aren’t displayed correctly, instead I see this: 
```
{MCP CANNEDMESSAGE ADD LOG}
Message 01
```

### CODE REVIEW

**Comment by DavidIQ** [comment]
Where do you see the log not displayed correctly? Should show up fine in the Moderator logs.

**Comment by Galixte** [comment]
@DavidIQ see my “Moderator log” page:
2017-09-20 11_20_36-moderator log - opera

The text from language key  isn’t displayed, it’s the name of the language key which is displayed.

Also, when I move an element (category or canned message) there isn’t separator between these in log message.

**Comment by iMattPro** [comment]
See https://github.com/phpbb-extensions/cannedmessages/pull/3

**Comment by DavidIQ** [comment]
I meant the moderator logs in the MCP. That's ok though and not related to this pr anyways.

**Pull request merged**
